version: '3.9'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app_network
    environment:
      FLASK_DEBUG: 1
      UPLOAD_FOLDER: /app/temp
      SECRET_KEY: "supersecretkey"
      OLLAMA_API_URL: "http://172.18.0.2:11434"  # Используем IP-адрес
      OLLAMA_MODEL: "llama3.1:8b"
      FLASK_PORT: 5000
      MAX_GENERATION_TIME: 300

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
